"""Physical systems for generating Hamiltonian trajectory data.

Each system defines:
- hamiltonian(q, p, **params): the true energy function
- dynamics(t, state, **params): Hamilton's equations dq/dt, dp/dt
- sample_initial_conditions(n, **kwargs): random (q0, p0) pairs
- default parameters

Trajectory data is generated by integrating Hamilton's equations with scipy.
"""

import numpy as np
from scipy.integrate import solve_ivp


# ---------------------------------------------------------------------------
# Mass-spring (1D harmonic oscillator): H = p²/2m + k*q²/2
# ---------------------------------------------------------------------------


def spring_hamiltonian(q, p, m=1.0, k=1.0):
    return p**2 / (2 * m) + k * q**2 / 2


def spring_dynamics(t, state, m=1.0, k=1.0):
    q, p = state
    dqdt = p / m
    dpdt = -k * q
    return [dqdt, dpdt]


def spring_initial_conditions(n, energy_range=(0.2, 2.0), rng=None):
    rng = np.random.default_rng(rng)
    energies = rng.uniform(*energy_range, size=n)
    angles = rng.uniform(0, 2 * np.pi, size=n)
    # For H = q²/2 + p²/2 (m=k=1), radius = sqrt(2E)
    r = np.sqrt(2 * energies)
    q0 = r * np.cos(angles)
    p0 = r * np.sin(angles)
    return np.column_stack([q0, p0])


# ---------------------------------------------------------------------------
# Ideal pendulum: H = p²/(2ml²) - mgl*cos(q)
# ---------------------------------------------------------------------------


def pendulum_hamiltonian(q, p, m=1.0, l=1.0, g=9.81):
    return p**2 / (2 * m * l**2) - m * g * l * np.cos(q)


def pendulum_dynamics(t, state, m=1.0, l=1.0, g=9.81):
    q, p = state
    dqdt = p / (m * l**2)
    dpdt = -m * g * l * np.sin(q)
    return [dqdt, dpdt]


def pendulum_initial_conditions(n, energy_range=(-8.0, 8.0), rng=None):
    """Sample initial conditions for the pendulum.

    energy_range is relative to the minimum of H (which is -mgl at q=0).
    We sample angles and set momentum to match a target energy.
    """
    rng = np.random.default_rng(rng)
    m, l, g = 1.0, 1.0, 9.81
    q0 = rng.uniform(-np.pi * 0.9, np.pi * 0.9, size=n)
    # Sample energies above the potential at q0
    V = -m * g * l * np.cos(q0)
    # Target energy: between V(q0) and some max (stay below separatrix for bounded orbits)
    E_max = m * g * l * 0.95  # just below the separatrix
    E_target = rng.uniform(V, np.maximum(V + 0.1, E_max), size=n)
    # p = sqrt(2*m*l²*(E - V))
    p0 = np.sqrt(2 * m * l**2 * (E_target - V))
    signs = rng.choice([-1, 1], size=n)
    p0 *= signs
    return np.column_stack([q0, p0])


# ---------------------------------------------------------------------------
# Two-body gravitational: H = |p|²/(2m) - GMm/|q|
# State is (qx, qy, px, py)
# ---------------------------------------------------------------------------

G_CONST = 1.0  # normalized gravitational constant
M_CENTRAL = 1.0  # central mass


def twobody_hamiltonian(q, p, m=1.0):
    """q, p are 2D vectors (or arrays with last dim = 2)."""
    q = np.asarray(q)
    p = np.asarray(p)
    r = np.sqrt(np.sum(q**2, axis=-1))
    kinetic = np.sum(p**2, axis=-1) / (2 * m)
    potential = -G_CONST * M_CENTRAL * m / r
    return kinetic + potential


def twobody_dynamics(t, state, m=1.0):
    qx, qy, px, py = state
    r = np.sqrt(qx**2 + qy**2)
    r3 = r**3
    dqxdt = px / m
    dqydt = py / m
    dpxdt = -G_CONST * M_CENTRAL * m * qx / r3
    dpydt = -G_CONST * M_CENTRAL * m * qy / r3
    return [dqxdt, dqydt, dpxdt, dpydt]


def twobody_initial_conditions(n, rng=None):
    """Generate initial conditions for bound Keplerian orbits."""
    rng = np.random.default_rng(rng)
    m = 1.0
    # Random radii and circular-ish velocities
    r0 = rng.uniform(1.0, 3.0, size=n)
    angle = rng.uniform(0, 2 * np.pi, size=n)
    qx = r0 * np.cos(angle)
    qy = r0 * np.sin(angle)
    # Circular orbit speed: v_c = sqrt(GM/r)
    v_circ = np.sqrt(G_CONST * M_CENTRAL / r0)
    # Perturb speed slightly for elliptical orbits
    speed = v_circ * rng.uniform(0.7, 1.1, size=n)
    # Velocity perpendicular to radius (+ small radial component)
    v_angle = angle + np.pi / 2 + rng.normal(0, 0.1, size=n)
    px = m * speed * np.cos(v_angle)
    py = m * speed * np.sin(v_angle)
    return np.column_stack([qx, qy, px, py])


# ---------------------------------------------------------------------------
# System registry
# ---------------------------------------------------------------------------

SYSTEMS = {
    "spring": {
        "hamiltonian": spring_hamiltonian,
        "dynamics": spring_dynamics,
        "initial_conditions": spring_initial_conditions,
        "state_dim": 2,
        "dof": 1,
        "params": {"m": 1.0, "k": 1.0},
    },
    "pendulum": {
        "hamiltonian": pendulum_hamiltonian,
        "dynamics": pendulum_dynamics,
        "initial_conditions": pendulum_initial_conditions,
        "state_dim": 2,
        "dof": 1,
        "params": {"m": 1.0, "l": 1.0, "g": 9.81},
    },
    "twobody": {
        "hamiltonian": twobody_hamiltonian,
        "dynamics": twobody_dynamics,
        "initial_conditions": twobody_initial_conditions,
        "state_dim": 4,
        "dof": 2,
        "params": {"m": 1.0},
    },
}


# ---------------------------------------------------------------------------
# Data generation
# ---------------------------------------------------------------------------


def generate_trajectories(
    system_name,
    n_trajectories=20,
    t_span=(0, 10),
    dt=0.1,
    noise_std=0.0,
    rng=None,
):
    """Generate trajectory data for a physical system.

    Returns:
        data: dict with keys 'states', 'derivatives', 'energies', 't'
            states: (N, state_dim) array of (q, p) values
            derivatives: (N, state_dim) array of (dq/dt, dp/dt) values
            energies: (N,) array of true Hamiltonian values
            t: time points used
    """
    rng = np.random.default_rng(rng)
    sys = SYSTEMS[system_name]
    dynamics = sys["dynamics"]
    hamiltonian = sys["hamiltonian"]
    params = sys["params"]
    state_dim = sys["state_dim"]
    dof = sys["dof"]

    t_eval = np.arange(t_span[0], t_span[1], dt)
    all_states = []
    all_derivs = []
    all_energies = []

    ics = sys["initial_conditions"](n_trajectories, rng=rng)

    for i in range(n_trajectories):
        y0 = ics[i]
        sol = solve_ivp(
            lambda t, y: dynamics(t, y, **params),
            t_span,
            y0,
            t_eval=t_eval,
            method="DOP853",
            rtol=1e-10,
            atol=1e-10,
        )
        if sol.status != 0:
            continue

        states = sol.y.T  # (T, state_dim)

        # Compute derivatives at each point
        derivs = np.array(
            [dynamics(0, s, **params) for s in states]
        )  # (T, state_dim)

        # Compute energies
        q = states[:, :dof]
        p = states[:, dof:]
        energies = hamiltonian(q, p, **params)

        all_states.append(states)
        all_derivs.append(derivs)
        all_energies.append(energies)

    all_states = np.concatenate(all_states, axis=0)
    all_derivs = np.concatenate(all_derivs, axis=0)
    all_energies = np.concatenate(all_energies, axis=0)

    # Add measurement noise
    if noise_std > 0:
        all_derivs += rng.normal(0, noise_std, all_derivs.shape)

    return {
        "states": all_states,
        "derivatives": all_derivs,
        "energies": all_energies,
        "t": t_eval,
        "state_dim": state_dim,
        "dof": dof,
    }
